#!/bin/sh
# openwrt_setup.sh - generated by hotspot_ms. Re-running it is safe (idempotent).
#
# Turns an OpenWrt box into a captive-portal gateway:
#   WAN  : __WAN_IFACE__ (untouched unless one-armed, see below)
#   LAN  : __LAN_IFACE__ over __LAN_PHY__ at __LAN_IP__/__LAN_CIDR_BITS__
#   portal: openNDS FAS -> __PORTAL_URL__/hotspot/login
#
# Two supported topologies:
#   Dual-NIC : WAN on __WAN_IFACE__, guest LAN bridged over __LAN_PHY__ (br-lan).
#   One-armed: guest LAN and WAN share one wire (__LAN_PHY__ == __WAN_IFACE__).
#              The router keeps a static address + upstream gateway and serves
#              DHCP itself, so guests still route THROUGH this box and openNDS
#              can enforce the portal. Meant for bench testing - production
#              boxes should use a dedicated guest NIC or VLANs.
#
# Safety: the script never removes SSH access from the subnet it is being run
# from, and refuses to guess when the topology does not match either mode.

set -u

WAN_IFACE="__WAN_IFACE__"
LAN_PHY="${HOTSPOT_LAN_PHY:-__LAN_PHY__}"
LAN_IP="__LAN_IP__"
LAN_CIDR="__LAN_CIDR__"
DHCP_START="__DHCP_START__"
DHCP_LIMIT="__DHCP_LIMIT__"

PORTAL_URL="__PORTAL_URL__"
PORTAL_HOST="__PORTAL_HOST__"
PORTAL_PORT="__PORTAL_PORT__"
FAS_SECURE="__FAS_SECURE__"

NAS_IDENTIFIER="__NAS_IDENTIFIER__"
NAS_SECRET="__NAS_SECRET__"
FAS_KEY="__FAS_KEY__"
GATEWAY_PORT="__GATEWAY_PORT__"
MAX_CLIENTS="__MAX_CLIENTS__"
SESSION_TIMEOUT="__SESSION_TIMEOUT__"
AGENT_INTERVAL="__AGENT_INTERVAL__"
# Ops-host SSH key, injected by the generator (empty on shared hosting).
HOTSPOT_SSH_KEY="${HOTSPOT_SSH_KEY:-__SSH_PUBKEY__}"

PROXY_PORTS="1080, 3128, 7777, 8243, 10808"
NFT_FRAGMENT="/usr/share/nftables.d/table-pre/99-hotspot-hardening.nft"
DRY_RUN=0
[ "${1:-}" = "--dry-run" ] && DRY_RUN=1

say() { printf '%s\n' "$*"; }
die() { say "ERROR: $*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

say "=============================================="
say " hotspot_ms router setup"
say " nas        : $NAS_IDENTIFIER"
say " portal     : $PORTAL_URL (secure level $FAS_SECURE)"
say " wan        : $WAN_IFACE"
say " guest lan  : over $LAN_PHY at $LAN_CIDR"
say "=============================================="

# --- preflight --------------------------------------------------------------
have uci || die "uci not found - is this OpenWrt?"
have ndsctl || die "openNDS is not installed (apk add opennds)"
have jsonfilter || say "WARNING: jsonfilter missing, the agent needs it (apk add jsonfilter)"

# Mode detection. HOTSPOT_LAN_PHY always wins so an operator can override.
ONE_ARMED=0
LAN_IFACE=""
if [ "$LAN_PHY" = "$WAN_IFACE" ]; then
	ONE_ARMED=1
	LAN_IFACE="$LAN_PHY"
	say "mode       : ONE-ARMED (guests share the WAN wire - test setup)"
elif ip link show "$LAN_PHY" >/dev/null 2>&1; then
	LAN_IFACE="br-lan"
	say "mode       : DEDICATED (guest LAN on $LAN_PHY, bridge $LAN_IFACE)"
else
	say "guest LAN interface '$LAN_PHY' not found."
	say "  - Plug in a USB ethernet adapter (drivers are usually already installed),"
	say "    check 'ip link' for the new device name, then re-run with:"
	say "      HOTSPOT_LAN_PHY=<device> sh <this-script>"
	die "refusing to continue: no guest LAN interface (falling back to WAN would cut the router off)."
fi

if [ "$ONE_ARMED" = "1" ]; then
	ip link show "$WAN_IFACE" >/dev/null 2>&1 || die "WAN interface '$WAN_IFACE' not found"
	WAN_GATEWAY="$(ip route show default 2>/dev/null | awk '{for (i = 1; i <= NF; i++) if ($i == "via") print $(i+1); exit}' | head -n1)"
	[ -n "$WAN_GATEWAY" ] || die "one-armed mode needs an upstream gateway (no default route found)"
	say "upstream gw: $WAN_GATEWAY"
else
	ip link show "$WAN_IFACE" >/dev/null 2>&1 || say "WARNING: WAN interface '$WAN_IFACE' not found"
fi

if [ "$DRY_RUN" = "1" ]; then
	say ""
	say "dry run: preflight passed, no changes applied."
	exit 0
fi

# --- 1. guest LAN -----------------------------------------------------------
say "1/7 configuring the guest LAN ($LAN_IFACE over $LAN_PHY)"
ip link set "$LAN_PHY" up 2>/dev/null || true

uci -q set network.lan=interface
uci set network.lan.proto='static'
uci set network.lan.device="$LAN_IFACE"
uci set network.lan.ipaddr="$LAN_IP"
uci set network.lan.netmask="__LAN_NETMASK__"
uci set network.lan.ip6assign='64' 2>/dev/null || true

if [ "$ONE_ARMED" = "1" ]; then
	# Guests and uplink share one wire. The router must stay the guests'
	# default gateway (enforcement) while still reaching the internet via
	# the upstream gateway. DHCP client on the same wire is disabled so it
	# cannot fight our static address.
	uci set network.lan.gateway="$WAN_GATEWAY"
	uci -q delete network.lan.dns
	uci add_list network.lan.dns="$WAN_GATEWAY"
	uci add_list network.lan.dns='1.1.1.1'
	uci set network.wan.proto='none' 2>/dev/null || true
	# No IPv6 RA/DHCPv6: upstream advertisements would bypass the portal.
	uci set dhcp.lan.ra='disabled' 2>/dev/null || true
	uci set dhcp.lan.dhcpv6='disabled' 2>/dev/null || true
else
	uci -q delete network.lan.gateway
	uci -q set network.brlan=device
	uci -q set network.brlan.name="$LAN_IFACE"
	uci -q set network.brlan.type='bridge'
	uci -q delete network.brlan.ports
	uci add_list network.brlan.ports="$LAN_PHY"
fi

uci -q set dhcp.lan=dhcp
uci set dhcp.lan.interface='lan'
uci set dhcp.lan.start="$DHCP_START"
uci set dhcp.lan.limit="$DHCP_LIMIT"
uci set dhcp.lan.leasetime='12h'
uci set dhcp.lan.dhcpv4='server'
uci commit network
uci commit dhcp

# --- 2. openNDS -------------------------------------------------------------
say "2/7 configuring openNDS"
uci -q set opennds.@opennds[0]=opennds
nds="opennds.@opennds[0]"
uci set "$nds".enabled='1'
uci set "$nds".gatewayinterface="$LAN_IFACE"
uci set "$nds".gatewayname="$NAS_IDENTIFIER"
uci set "$nds".gatewayport="$GATEWAY_PORT"
uci set "$nds".maxclients="$MAX_CLIENTS"
uci set "$nds".sessiontimeout="$SESSION_TIMEOUT"
uci set "$nds".fasport="$PORTAL_PORT"
uci set "$nds".faspath='/hotspot/login'
uci set "$nds".faskey="$FAS_KEY"
# Level 1 (http) and level 4 (https) both send the base64 "fas" payload this
# portal decodes. Levels 2/3 are AES-encrypted and are not supported.
uci set "$nds".fas_secure_enabled="$FAS_SECURE"
uci -q delete "$nds".fasremotefqdn
uci set "$nds".fasremoteip="$PORTAL_HOST"

# Walled garden: only the portal itself. DNS/DHCP/SSH to the router are always
# permitted by openNDS, so no blanket port 53 rule is added (that would open
# the door to DNS tunnelling).
uci -q delete "$nds".preauthenticated_users
uci add_list "$nds".preauthenticated_users="allow tcp port $PORTAL_PORT to $PORTAL_HOST"
uci commit opennds

# --- 3. agent ---------------------------------------------------------------
say "3/7 installing the hotspot agent"
cat <<'HOTSPOT_AGENT_EOF' > /usr/bin/hotspot-agent.sh
__AGENT_BODY__
HOTSPOT_AGENT_EOF
chmod 0755 /usr/bin/hotspot-agent.sh

cat <<EOF > /etc/hotspot.conf
PORTAL_URL="$PORTAL_URL"
NAS_IDENTIFIER="$NAS_IDENTIFIER"
NAS_SECRET="$NAS_SECRET"
POLL_INTERVAL="$AGENT_INTERVAL"
EOF
chmod 0600 /etc/hotspot.conf

# Remember the detected topology so re-runs without HOTSPOT_LAN_PHY keep working.
cat <<EOF > /etc/hotspot.mode
LAN_PHY="$LAN_PHY"
ONE_ARMED="$ONE_ARMED"
EOF

cat <<'INIT_EOF' > /etc/init.d/hotspot-agent
#!/bin/sh /etc/rc.common

USE_PROCD=1
START=97
STOP=10

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/hotspot-agent.sh
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
INIT_EOF
chmod 0755 /etc/init.d/hotspot-agent

# --- 4. hardening -----------------------------------------------------------
say "4/7 applying anti-tethering and bypass blocks"
mkdir -p "$(dirname "$NFT_FRAGMENT")"
cat <<EOF > "$NFT_FRAGMENT"
chain hotspot_hardening {
  type filter hook prerouting priority mangle; policy accept;

  # Common proxy/VPN tethering-bypass ports (NetShare, PDANet, ...).
  iifname "$LAN_IFACE" tcp dport { $PROXY_PORTS } counter drop
  iifname "$LAN_IFACE" udp dport { $PROXY_PORTS } counter drop

  # A guest packet that already hopped once (TTL 63) came from behind the
  # guest's own router, i.e. they are sharing the connection.
  iifname "$LAN_IFACE" ip ttl 63 counter drop
  iifname "$LAN_IFACE" ip6 hoplimit 63 counter drop
}
EOF

if [ -f /etc/config/wireless ]; then
	for section in $(uci show wireless 2>/dev/null | sed -n 's/^wireless\.\([^=]*\)=wifi-iface$/\1/p'); do
		uci -q set "wireless.$section.isolate='1'" || true
	done
	uci -q commit wireless
fi

# --- 5. firewall ------------------------------------------------------------
say "5/7 firewall: hardening reload + SSH hygiene"

# Router SSH keys: passwordless login for the ops host, password auth kept
# available for console recovery. Idempotent.
if [ -n "${HOTSPOT_SSH_KEY:-}" ]; then
	mkdir -p /etc/dropbear
	touch /etc/dropbear/authorized_keys
	chmod 0600 /etc/dropbear/authorized_keys
	grep -qxF "$HOTSPOT_SSH_KEY" /etc/dropbear/authorized_keys || \
		printf '%s\n' "$HOTSPOT_SSH_KEY" >> /etc/dropbear/authorized_keys
	say "  ssh: authorized_keys updated"
fi
# Set a strong root password if none is set (empty password = open door).
if ! ( uci -q get system.@system[0]._rootpw_set >/dev/null 2>&1 ); then
	if passwd -S root 2>/dev/null | grep -q " root .*P "; then
		uci set system.@system[0]._rootpw_set='1'
		uci commit system
	else
		say "  WARNING: root has NO password. Set one now: passwd"
	fi
fi

# Management rules. Dual-NIC: SSH allowed from WAN (ops host) and the guest
# side is treated as untrusted. One-armed: everything is on one wire, so SSH
# stays reachable from it - otherwise this very session would be locked out.
if [ "$ONE_ARMED" = "1" ]; then
	say "  one-armed: dropbear stays reachable from the LAN wire (test mode)"
else
	uci -q delete firewall.hotspot_mgmt_wan
	uci set firewall.hotspot_mgmt_wan=rule
	uci set firewall.hotspot_mgmt_wan.name='Allow-SSH-Mgmt'
	uci set firewall.hotspot_mgmt_wan.src='wan'
	uci set firewall.hotspot_mgmt_wan.proto='tcp'
	uci set firewall.hotspot_mgmt_wan.dest_port='22'
	uci set firewall.hotspot_mgmt_wan.target='ACCEPT'
	uci commit firewall
fi

# Apply the network config detached from this SSH session. A synchronous
# reload bounces the link and, if the SSH client dies mid-reload, netifd is
# left half-applied and the box drops off the network (seen in the field).
# Detached + logged, the reload always finishes and the box always comes back.
if [ "$ONE_ARMED" = "1" ]; then
	say "  applying network config detached (link will blip)"
	nohup sh -c '/etc/init.d/network restart >/tmp/hotspot-network-reload.log 2>&1; /etc/init.d/dnsmasq restart >>/tmp/hotspot-network-reload.log 2>&1' >/dev/null 2>&1 &
	sleep 5
else
	/etc/init.d/network reload || say "WARNING: network reload returned an error"
fi

if ! fw4 -q reload 2>/dev/null; then
	say "WARNING: firewall rejected the hardening fragment - removing it"
	rm -f "$NFT_FRAGMENT"
	fw4 -q reload 2>/dev/null || true
fi

# --- 6. services ------------------------------------------------------------
say "6/7 starting openNDS and the agent"
/etc/init.d/opennds enable 2>/dev/null || true
/etc/init.d/opennds restart || say "WARNING: openNDS failed to start - check 'logread -e opennds'"
/etc/init.d/hotspot-agent enable 2>/dev/null || true
/etc/init.d/hotspot-agent restart || say "WARNING: the hotspot agent failed to start"

# --- 7. verify --------------------------------------------------------------
say "7/7 verifying"
sleep 3
ip -4 addr show "$LAN_IFACE" 2>/dev/null | grep -q "inet $LAN_IP" \
	&& say "  ok: $LAN_IFACE is up at $LAN_IP" \
	|| say "  WARN: $LAN_IFACE has no address yet"
ndsctl status >/dev/null 2>&1 \
	&& say "  ok: openNDS is answering" \
	|| say "  WARN: openNDS is not answering (logread -e opennds)"
pgrep -f hotspot-agent.sh >/dev/null 2>&1 \
	&& say "  ok: hotspot agent is running" \
	|| say "  WARN: hotspot agent is not running"
if have wget; then
	wget -qO- --timeout=8 "$PORTAL_URL/api/method/hotspot_ms.api.portal.get_packages" | grep -q '"ok"' \
		&& say "  ok: portal $PORTAL_URL is reachable from the router" \
		|| say "  WARN: cannot reach the portal at $PORTAL_URL (router_sync will fail)"
fi

say ""
say "Done. Guest clients on $LAN_IFACE now hit the captive portal."
[ "$ONE_ARMED" = "1" ] && say "NOTE: one-armed test mode - guests share your main LAN wire."
say ""
say "Useful checks:"
say "  ndsctl status | head -20"
say "  logread -e opennds | tail -n 20"
say "  logread -e hotspot-agent | tail -n 20"
say "  hotspot-agent.sh --once"
